name: MainJob
on:
  push:
    branches: [ '**' ]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet-version: ['6.0.x' ]
    steps:
      - uses: actions/checkout@v3
      - name: Setup dotnet
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '6.0.x'
      - name: Build
        run: dotnet build TodoFramework.sln
      - name: Check format issues
        run: dotnet format --verify-no-changes -v d TodoFramework.sln

      - name: Setup Secrets
        run: |
          echo "TODO-LY-EMAIL=${{secrets.TODO_LY_EMAIL}}" >> $GITHUB_ENV
          echo "TODO-LY-PASS=${{secrets.TODO_LY_PASS}}" >> $GITHUB_ENV
          echo "DriverType=${{secrets.DRIVERTYPE}}" >> $GITHUB_ENV
          echo "DriverMode=Headless" >> $GITHUB_ENV
      # - name: Run UI tests
      #   run: dotnet test 3.Tests/UI --no-build --no-restore --filter "Category=Smoke | Category=Regression"
      - name: Selenium docker grid setup
        run: |
          docker-compose -f 1.Core/Docker/hub.yml up -d
          docker-compose -f 1.Core/Docker/$DRIVERTYPE up -d
      - name: Run Tests
        run: dotnet test 3.Tests/UI
      - name: End docker sessions
        run: |
          docker-compose -f 1.Core/Docker/hub.yml stop
          docker-compose -f 1.Core/Docker/$DRIVERTYPE.yml down --remove-orphans
          docker container prune -f
