name: UI Test execution

on:
  workflow_call:

jobs:
  Run-UI-Tests:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v3
    - name: Setup dotnet
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '6.0.x'
    - name: Install tools
      run: dotnet tool update --global SpecFlow.Plus.LivingDoc.CLI
    - name: Setup Secrets
      run: |
        echo "TODO-LY-EMAIL=${{secrets.TODO_LY_EMAIL}}" >> $GITHUB_ENV
        echo "TODO-LY-PASS=${{secrets.TODO_LY_PASS}}" >> $GITHUB_ENV
        echo "BROWSERSTACK-USERNAME=${{secrets.BROWSERSTACK_USERNAME}}" >> $GITHUB_ENV
        echo "BROWSERSTACK-ACCESSKEY=${{secrets.BROWSERSTACK_ACCESSKEY}}" >> $GITHUB_ENV
        echo "DriverType=Chrome" >> $GITHUB_ENV
        echo "DriverLocation=Remote" >> $GITHUB_ENV
        echo "DriverMode=Headless" >> $GITHUB_ENV
    - name: Selenium docker grid setup
      run: |
        docker-compose -f 1.Core/Docker/hub.yml up -d
        docker-compose -f 1.Core/Docker/${DriverType}.yml up -d
    - name: Build
      run: dotnet build TodoFramework.sln
    - name: Run UI Tests
      run: dotnet test 3.Tests/UI --no-build --no-restore
    - name: End docker sessions
      if: always()
      run: |
        docker-compose -f 1.Core/Docker/hub.yml stop
        docker-compose -f 1.Core/Docker/${DriverType}.yml down --remove-orphans
        docker container prune
    - name: Get Allure history
      uses: actions/checkout@v3
      if: always()
      continue-on-error: true
      with:
        ref: gh-pages
        path: gh-pages
    - name: Allure Report action from marketplace
      uses: simple-elf/allure-report-action@master
      if: always()
      id: allure-report
      with:
        allure_results: 3.Tests/UI/bin/Debug/net6.0/allure-results
        gh_pages: gh-pages
        allure_report: allure-report
        allure_history: allure-history
    - name: Deploy report to Github Pages
      if: always()
      uses: peaceiris/actions-gh-pages@v2
      env:
        PERSONAL_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        PUBLISH_BRANCH: gh-pages
        PUBLISH_DIR: allure-history
    - name: Create Livingdoc reports
      if: always()
      run: livingdoc feature-folder 3.Tests/UI -t 3.Tests/UI/bin/Debug/net6.0/TestExecution.json --output 3.Tests/UI/ReportOutputs/LivingDoc.html
    - name: Upload LivingDoc report file
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: Run#${{ github.run_number }}_LivingDoc.html
        path: 3.Tests/UI/ReportOutputs/LivingDoc.html
    - name: Upload failed test screenshots report file
      if: failure()
      uses: actions/upload-artifact@v3
      with:
        name: Screenshots
        path: 3.Tests/UI/Assets
    - name: Upload Latest Logs file
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: TestsLogs
        path: 3.Tests/UI/bin/Debug/net6.0/Logs/Latest*.txt